version: '3.8'

services:
  packet_sender2:
    image: traffic_checker
    container_name: Packet_sender2
    restart: unless-stopped
    tty: true  
    volumes:
    - .:/home   
    networks:
    - packet_sender_net
    #ipv4_address: 192.168.140.3
    command: >
      sh -c "
      python3 /home/PackerSenderVlan.py &
      wait
      "
networks:
  packet_sender_net:
    external:
      name: sender-macvlan2
